### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by franknoe** [bhmm/bhmm#14]
This repository doesn't appear to have automatic test runs activated. I guess this is because the old bhmm package was renamed into  bhmm-force-spectroscopy-manuscript, so the test configuration is probably there. I think we should have the bhmm tests here and instead only test-run the example scripts in bhmm-force-spectroscopy-manuscript. @jchodera  or @marscher  can either of you do that?

**Comment by jchodera** [comment]
I'll look into this!

To be clear: You're looking for me to enable testing beyond the nosetests that are [performed during the conda package build](https://github.com/bhmm/bhmm/blob/master/devtools/conda-recipe/meta.yaml#L34)?

```
nosetests bhmm --nocapture --verbosity=2 --with-doctest
```

**Comment by jchodera** [comment]
Oh, I see---travis is just disabled.

**Comment by franknoe** [comment]
No - this is an old issue and it got fixed some time ago. I closed it.
