### ISSUE TITLE
new release for updated dependencies?

### ISSUE THREAD

**Issue by marscher** [bhmm/bhmm#18]
Since 0.4.2 we have removed the dependencies for scikit-learn and pyemma. Shall we trigger a new release?

**Comment by marscher** [comment]
I'll suggest releasing 0.5 after we have achieved Py3k compatibility.

**Comment by jchodera** [comment]
Sounds great.  Working on this.

**Comment by jchodera** [comment]
Actually, you're more familiar with the changes since 0.4.2, @marscher---can you prepare the release?

**Comment by jchodera** [comment]
(I've just added you to 'owners', so you have permissions to do so.)

**Comment by marscher** [comment]
Can you write a changelog entry? Actually I've no clue what has been
changed but for my PRs.

**Comment by jchodera** [comment]
Ah, OK---thought you might know better than I.  I'll just tackle the release.   Thanks!
