### ISSUE TITLE
Docs hosting?

### ISSUE THREAD

**Issue by jchodera** [bhmm/bhmm#2]
Where should we host the docs for this toolkit?

Would we be OK with [pythonhosted](http://pythonhosted.org) or [readthedocs](https://readthedocs.org)?  Or do we want to register a domain name and put the docs there?

**Comment by franknoe** [comment]
I guess pythonhosted or readthedocs would be ok as this is a core 
package. It would be interesting to create a separate domain name for 
single-molecule HMM analysis and then link to different packages (force 
spectroscopy, smFRET, core package) there. Maybe it could also become an 
omnia application - let's see.

I have no opinion about pythonhosted vs readthedocs. What do you recommend?

Am 09/07/15 um 14:25 schrieb John Chodera:

> Where should we host the docs for this toolkit?
> 
> Would we be OK with pythonhosted http://pythonhosted.org or 
> readthedocs https://readthedocs.org? Or do we want to register a 
> domain name and put the docs there?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/2.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
We have more experience with either S3 hosting (requires a domain name to
set it up the way I know how) or readthedocs.  Will try readthedocs first.

**Comment by franknoe** [comment]
ok

Am 09/07/15 um 14:36 schrieb John Chodera:

> We have more experience with either S3 hosting (requires a domain name to
> set it up the way I know how) or readthedocs. Will try readthedocs first.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/2#issuecomment-119947072.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@jchodera if you give me the permission for this repo, I can add the readthedocs hook to build the docs over there.

**Comment by marscher** [comment]
https://bhmm.readthedocs.io/en/latest/#

**Comment by jchodera** [comment]
@marscher You're an owner of the GitHub org, so you should have full permissions here! Or did you mean at `readthedocs.io`?

**Comment by marscher** [comment]
On 12/11/2017 07:02 PM, John Chodera wrote:
> @marscher <https://github.com/marscher> You're an owner of the GitHub
> org, so you should have full permissions here! Or did you mean at
> |readthedocs.io|?

Sorry for the noise, Readthedocs displayed that I do not have
permissions but it was a bug. Thanks!
