### ISSUE TITLE
HMM initialization is broken

### ISSUE THREAD

**Issue by anntzer** [bhmm/bhmm#36]
from the current master:

```
In [10]: estimate_hmm([np.r_[np.random.randn(10) + 10, np.random.randn(10) + 11]], 2)
<... elided>
/usr/lib/python3.5/site-packages/msmtools/estimation/api.py in transition_matrix(C, reversible, mu, method, **kwargs)
    939         if mu is None:
    940             if sparse_computation:
--> 941                 T = sparse.mle_trev.mle_trev(C, **kwargs)
    942             else:
    943                 T = dense.mle_trev.mle_trev(C, **kwargs)

msmtools/estimation/sparse/mle_trev.pyx in msmtools.estimation.sparse.mle_trev.mle_trev (msmtools/estimation/sparse/mle_trev.c:1645)()

AssertionError: C must be strongly connected
```

Turns out the shipped version of sklearn.mixture.GMM fits very poorly this mixture of a gaussian of mean 10 and a gaussian of mean 11, returning instead

```
ipdb> p gmm.means_
array([[ 10.30914931],
       [  0.        ]])
```

Switching to the latest version of scikit-learn solves the issue.  Any reason you don't want to simply rely on it as a dependency?

**Comment by franknoe** [comment]
It's probably an issue with the k-means initialization of the GMM. We'll 
check.

Am 04/03/16 um 05:24 schrieb Antony Lee:

> from the current master:
> 
> |In [10]: estimate_hmm([np.r_[np.random.randn(10) + 10, 
> np.random.randn(10) + 11]], 2) <... elided> 
> /usr/lib/python3.5/site-packages/msmtools/estimation/api.py in 
> transition_matrix(C, reversible, mu, method, *_kwargs) 939 if mu is 
> None: 940 if sparse_computation: --> 941 T = 
> sparse.mle_trev.mle_trev(C, *_kwargs) 942 else: 943 T = 
> dense.mle_trev.mle_trev(C, **kwargs) 
> msmtools/estimation/sparse/mle_trev.pyx in 
> msmtools.estimation.sparse.mle_trev.mle_trev 
> (msmtools/estimation/sparse/mle_trev.c:1645)() AssertionError: C must 
> be strongly connected |
> 
> Turns out the shipped version of sklearn.mixture.GMM fits very poorly 
> this mixture of a gaussian of mean 10 and a gaussian of mean 11, 
> returning instead
> 
> |ipdb> p gmm.means_ array([[ 10.30914931], [ 0. ]]) |
> 
> Switching to the latest version of scikit-learn solves the issue. Any 
> reason you don't want to simply rely on it as a dependency?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/36.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
@marscher and @clonker, can you check the k-means implementation 
integrated in bhmm with this example and compare with the one that 
sklearns to initialize GMMs? I think the problem might be that we get an 
empty cluster in this case.

The reason we don't want to create a dependency on sklearn is that we 
would only need it for this simple functionality and bhmm is a core 
package. That doesn't justify creating a dependency on a huge package. 
Note that we have also changed the GMM code to employ a different 
(faster) k-means implementation. bhmm is in a pre-release state, so I'm 
confident we can resolve these hickups before a stable release.

Am 04/03/16 um 05:24 schrieb Antony Lee:

> from the current master:
> 
> |In [10]: estimate_hmm([np.r_[np.random.randn(10) + 10, 
> np.random.randn(10) + 11]], 2) <... elided> 
> /usr/lib/python3.5/site-packages/msmtools/estimation/api.py in 
> transition_matrix(C, reversible, mu, method, *_kwargs) 939 if mu is 
> None: 940 if sparse_computation: --> 941 T = 
> sparse.mle_trev.mle_trev(C, *_kwargs) 942 else: 943 T = 
> dense.mle_trev.mle_trev(C, **kwargs) 
> msmtools/estimation/sparse/mle_trev.pyx in 
> msmtools.estimation.sparse.mle_trev.mle_trev 
> (msmtools/estimation/sparse/mle_trev.c:1645)() AssertionError: C must 
> be strongly connected |
> 
> Turns out the shipped version of sklearn.mixture.GMM fits very poorly 
> this mixture of a gaussian of mean 10 and a gaussian of mean 11, 
> returning instead
> 
> |ipdb> p gmm.means_ array([[ 10.30914931], [ 0. ]]) |
> 
> Switching to the latest version of scikit-learn solves the issue. Any 
> reason you don't want to simply rely on it as a dependency?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/36.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Hi, the issue is with the dtypes.. when it arrives at the initialize-centers method in the gmm code, the data's dtype is float64, while the initialize centers method relies on float32.

I also noticed that sklearn's gmm code seems to actually execute the clustering, while our code only assigns the centers.. is this intended?

**Comment by franknoe** [comment]
Am 04/03/16 um 15:04 schrieb Moritz Hoffmann:

> Hi, the issue is with the dtypes.. when it arrives at the 
> initialize-centers method in the gmm code, the data's dtype is 
> float64, while the initialize centers method relies on float32.
> 
> Why does that leat to the observed issue? I don't think precision is a 
> problem at this point.
> 
> I also noticed that sklearn's gmm code seems to actually execute the 
> clustering, while our code only assigns the centers.. is this intended?
> 
> I think we just need some sort of not-too-bad clustering as an 
> initialization. If the kmeans++ discretization is sufficient, I don't 
> think we need clustering. But apparently in this example it doesn't 
> work. However, if one cluster is unassigned, I don't know how a 
> subsequent kmeans iteration could recover from that.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/36#issuecomment-192294810.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Its a problem because the data is read and interpreted as floats but is actually stored as doubles, so it leads to strange values:

```
# the actual data:
[array([  9.35199317,   8.63479719,  10.40255769,  10.76410824, 12.00298619,   9.40413402,  10.24054119,   9.91014595, 9.74937995,   9.98996941,  10.90704601,  11.13170579, 8.96708971,  10.86745951,   9.70979846,  11.43157971, 10.36417482,  12.94998945,  10.71909602,  11.10459634])]
# interpreted as floats:
-0.000000, 2.574872, -0.000000, 2.581804, -0.000000, 2.504323, -0.000000, 2.572391, 36893488147419103232.000000, 2.576740, 36893488147419103232.000000, 2.506025, 36893488147419103232.000000, 2.589205, 0.000000, 2.534283, -2.000000, 2.569619, 0.000000, 2.636055
```

If one changes in "_external/sklearn/mixture/gmm.py" the line

``` python
centers = init_centers(X, 'euclidean', self.n_components)
```

to

``` python
centers = init_centers(X.astype(np.float32), 'euclidean', self.n_components)
```

the means are comparable to the ones that sklearn generates and the example works.

**Comment by franknoe** [comment]
I see, that explains some random doctest failures. Can you fix it?

Best
Frank.

Am 04/03/16 um 15:53 schrieb Moritz Hoffmann:

> Its a problem because the data is read and interpreted as floats but 
> is actually stored as doubles, so it leads to strange values:
> 
> |# the actual data: [array([ 9.35199317, 8.63479719, 10.40255769, 
> 10.76410824, 12.00298619, 9.40413402, 10.24054119, 9.91014595, 
> 9.74937995, 9.98996941, 10.90704601, 11.13170579, 8.96708971, 
> 10.86745951, 9.70979846, 11.43157971, 10.36417482, 12.94998945, 
> 10.71909602, 11.10459634])] # interpreted as floats: -0.000000, 
> 2.574872, -0.000000, 2.581804, -0.000000, 2.504323, -0.000000, 
> 2.572391, 36893488147419103232.000000, 2.576740, 
> 36893488147419103232.000000, 2.506025, 36893488147419103232.000000, 
> 2.589205, 0.000000, 2.534283, -2.000000, 2.569619, 0.000000, 2.636055 |
> 
> If one changes in "_external/sklearn/mixture/gmm.py" the line
> 
> centers=  init_centers(X,'euclidean',self.n_components)
> 
> to
> 
> centers=  init_centers(X.astype(np.float32),'euclidean',self.n_components)
> 
> the means are comparable to the ones that sklearn generates and the 
> example works.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/36#issuecomment-192308796.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Done by #37
