### ISSUE TITLE
SampledHMM object has no attribute _stationary

### ISSUE THREAD

**Issue by ChayaSt** [bhmm/bhmm#39]
The if clause in `sationary_distribution_samples(self)` relies on the `self._stationary` attribute:
https://github.com/bhmm/bhmm/blob/master/bhmm/hmm/generic_sampled_hmm.py#L95

But neither  `HMM` object not the `SampledHMM` object has this attribute. Is is supposed to be `is_stationary`?

**Comment by franknoe** [comment]
Yes, that would be a solution for now. That code and API is subject to 
change though.

Am 28/03/16 um 20:33 schrieb ChayaSt:

> The if clause in |sationary_distribution_samples(self)| relies on the 
> |self._stationary| attribute:
> https://github.com/bhmm/bhmm/blob/master/bhmm/hmm/generic_sampled_hmm.py#L95
> 
> But neither |HMM| object not the |SampledHMM| object has this 
> attribute. Is is supposed to be |is_stationary|?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/39

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ChayaSt** [comment]
I changed it. Should I open  PR?

**Comment by franknoe** [comment]
Yes, thanks!

Am 28/03/16 um 20:45 schrieb ChayaSt:

> I changed it. Should I open PR?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/39#issuecomment-202525392

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Addressed by #40
