### ISSUE TITLE
bhmm-dev package on binstar

### ISSUE THREAD

**Issue by jchodera** [bhmm/bhmm#5]
I've made the necessary changes to have travis build development packages and push them to binstar:
https://binstar.org/omnia/bhmm-dev/files

Should be building now.

**Comment by franknoe** [comment]
great, thanks!

Am 09/07/15 um 15:35 schrieb John Chodera:

> I've made the necessary changes to have travis build development 
> packages and push them to binstar:
> https://binstar.org/omnia/bhmm-dev/files
> 
> Should be building now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/5.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
