### ISSUE TITLE
Problem with sample path

### ISSUE THREAD

**Issue by clonker** [bhmm/bhmm#53]
Hi guys,

think I found a bug in the sample path c implementation: https://github.com/bhmm/bhmm/blob/9804d18c2ddb684fb4d90b544cc209617a89ca9a/bhmm/hidden/impl_c/_hidden.c#L338

Whenever sample path is called, the random generator is seeded (which is fine, in principle), however the seeding that is used here takes the amount of seconds since 1970, i.e., if im correct sample path is completely deterministic within a single second. Since sampling procedure calls this method (on my machine) up to 150 times per second, this can bias the results.

**Comment by franknoe** [comment]
Ah good catch :)

**Comment by franknoe** [comment]
This is my code actually.

**Comment by clonker** [comment]
Solved with PR #54
