### ISSUE TITLE
compilation fails with visual c++

### ISSUE THREAD

**Issue by marscher** [bhmm/bhmm#6]
```
./bhmm/output_models/impl_c/_gaussian.c(17) : error C2065: 'M_PI' : undeclared identifier
```

https://stackoverflow.com/questions/806145/how-do-i-access-math-constants-eg-m-pi-in-visual-c-2008

**Comment by franknoe** [comment]
Does |#define _USE_MATH_DEFINES|
then work across all platforms?

Am 09/07/15 um 15:42 schrieb Martin K. Scherer:

> |./bhmm/output_models/impl_c/_gaussian.c(17) : error C2065: 'M_PI' : undeclared identifier
> |
> 
> https://stackoverflow.com/questions/806145/how-do-i-access-math-constants-eg-m-pi-in-visual-c-2008
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/issues/6.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
it is just a define, it should not hurt other compilers.
